spring:
  mongodb:
    uri: mongodb://localhost:27017/logistics_db?directConnection=true
  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: ""

spring.cloud.aws:
  region:
    static: us-east-1
  credentials:
    access-key: test
    secret-key: test
  endpoint: http://localhost:4566
  sqs:
    endpoint: http://localhost:4566

app:
  viacep:
    base-url: https://viacep.com.br/ws
    timeout-ms: 5000
    retry-max-attempts: 3
  redis:
    cep-cache:
      ttl-hours: 24

logging:
  level:
    root: INFO
    br.furb: INFO
    io.awspring.cloud: INFO
